### ISSUE TITLE
SDL2.dll error

### ISSUE THREAD

**Issue by zTecna** [fishfight/FishLauncher#6]
When opening the executable I get the following error:
**"code execution cannot continue because sdl2.dll was not found."**
I don't know if I forgot to install some program necessary to run the game.

**Comment by zTecna** [comment]
remembering that this same error happens when trying to "play" on the launcher

**Comment by Borber** [comment]
Me too, on v0.4.1, due to my network, I didn't test the older version

**Comment by orhun** [comment]
`FishLauncher` is only responsible for downloading the latest release from [FishFight](https://github.com/fishfight/FishFight) upstream repository and running the pre-built binary. This error occurs due to Fish Fight binary being dependent on [SDL2](https://www.libsdl.org/download-2.0.php). The solution is downloading `SDL2.dll` and placing it next to the executable which is located in `C:\Users\<User>\.fishfight` after you install the game via launcher.

I'll submit a PR to `FishFight` so that Windows releases will contain `SDL2.dll` in the next releases.

**Comment by orhun** [comment]
SDL2 is removed along with the latest changes in the upstream repository. This issue won't be a problem for the upcoming releases.
